spring.application.name=Haven Clinic
server.port=8088

spring.datasource.url=jdbc:h2:file:./data/haven;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.thymeleaf.cache=false

fluxa.demo.email=demo@haven.clinic
fluxa.demo.password=demo1234
